# Generated by Django 5.0.6 on 2024-05-15 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courseApp', '0002_remove_course_prerequisites_course_prerequisites'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='prerequisites',
        ),
        migrations.AddField(
            model_name='course',
            name='prerequisites',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
