# Generated by Django 5.0.6 on 2024-05-16 08:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courseApp', '0003_remove_course_prerequisites_course_prerequisites'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='scheduleID',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='courseApp.courseschedule'),
        ),
    ]
