# Generated by Django 5.0.6 on 2024-05-16 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courseApp', '0005_alter_student_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courseschedule',
            name='endTime',
            field=models.TimeField(null=True),
        ),
        migrations.AlterField(
            model_name='courseschedule',
            name='roomNo',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='courseschedule',
            name='startTime',
            field=models.TimeField(null=True),
        ),
    ]
