# Generated by Django 5.0.6 on 2024-05-17 08:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courseApp', '0009_alter_studentreg_course_alter_studentreg_student'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentreg',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courseApp.course'),
        ),
        migrations.AlterField(
            model_name='studentreg',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courseApp.student'),
        ),
    ]
