# Generated by Django 5.0.6 on 2024-05-20 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courseApp', '0010_alter_studentreg_course_alter_studentreg_student'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentreg',
            name='comleted',
            field=models.BooleanField(default=False),
        ),
        migrations.RemoveField(
            model_name='course',
            name='prerequisites',
        ),
        migrations.AlterField(
            model_name='courseschedule',
            name='endTime',
            field=models.TimeField(default='00:00:00'),
        ),
        migrations.AlterField(
            model_name='courseschedule',
            name='startTime',
            field=models.TimeField(default='00:00:00'),
        ),
        migrations.AlterField(
            model_name='student',
            name='name',
            field=models.CharField(default='studentName', max_length=100),
        ),
        migrations.AddField(
            model_name='course',
            name='prerequisites',
            field=models.ManyToManyField(blank=True, related_name='prerequisite_for', to='courseApp.course'),
        ),
    ]
