# Generated by Django 5.0.6 on 2024-05-20 22:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courseApp', '0012_rename_comleted_studentreg_completed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='scheduleID',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='courseApp.courseschedule'),
        ),
    ]
