# Generated by Django 5.0.6 on 2024-05-20 22:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courseApp', '0013_alter_course_scheduleid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='scheduleID',
            field=models.ForeignKey(blank=True, default=0, on_delete=django.db.models.deletion.CASCADE, to='courseApp.courseschedule'),
        ),
    ]
