# Generated by Django 5.0.6 on 2024-05-21 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courseApp', '0015_alter_course_scheduleid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='prerequisites',
            field=models.ManyToManyField(blank=True, null=True, related_name='prerequisite_for', to='courseApp.course'),
        ),
    ]
