# Generated by Django 5.0.6 on 2024-05-21 18:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courseApp', '0017_alter_course_prerequisites'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='scheduleID',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='courseApp.courseschedule'),
        ),
    ]
