# Generated by Django 5.0.6 on 2024-05-23 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courseApp', '0020_alter_student_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courseschedule',
            name='days',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='courseschedule',
            name='endTime',
            field=models.TimeField(blank=True, default='00:00:00'),
        ),
        migrations.AlterField(
            model_name='courseschedule',
            name='roomNo',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='courseschedule',
            name='startTime',
            field=models.TimeField(blank=True, default='00:00:00'),
        ),
    ]
