# Generated by Django 5.0.6 on 2024-05-23 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courseApp', '0021_alter_courseschedule_days_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courseschedule',
            name='days',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='courseschedule',
            name='endTime',
            field=models.TimeField(blank=True, default='00:00:00', null=True),
        ),
        migrations.AlterField(
            model_name='courseschedule',
            name='startTime',
            field=models.TimeField(blank=True, default='00:00:00', null=True),
        ),
    ]
