# Generated by Django 5.0.6 on 2024-05-24 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courseApp', '0022_alter_courseschedule_days_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courseschedule',
            name='endTime',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='courseschedule',
            name='startTime',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
